#python phedex.py
#python tally_access_info.py --source cmssw --dates "2020/01/*"
#python tally_access_info.py --source cmssw --dates "2020/02/*"
#python tally_access_info.py --source cmssw --dates "2020/03/*"
#python tally_access_info.py --source cmssw --dates "2020/04/*"
#python tally_access_info.py --source cmssw --dates "2020/05/*"
#python tally_access_info.py --source cmssw --dates "2020/06/*"
#python tally_access_info.py --source cmssw --dates "2020/07/*"
#python tally_access_info.py --source cmssw --dates "2020/08/*"
#python tally_access_info.py --source cmssw --dates "2020/09/*"
#python tally_access_info.py --source cmssw --dates "2020/10/*"
#python tally_access_info.py --source cmssw --dates "2020/11/*"
#python tally_access_info.py --source cmssw --dates "2020/12/*"

#python tally_access_info.py --source xrootd --dates "2020/01/*"
#python tally_access_info.py --source xrootd --dates "2020/02/*"
#python tally_access_info.py --source xrootd --dates "2020/03/*"
#python tally_access_info.py --source xrootd --dates "2020/04/*"
#python tally_access_info.py --source xrootd --dates "2020/05/*"
#python tally_access_info.py --source xrootd --dates "2020/06/*"
#python tally_access_info.py --source xrootd --dates "2020/07/*"
#python tally_access_info.py --source xrootd --dates "2020/08/*"
#python tally_access_info.py --source xrootd --dates "2020/09/*"
#python tally_access_info.py --source xrootd --dates "2020/10/*"
#python tally_access_info.py --source xrootd --dates "2020/11/*"
#python tally_access_info.py --source xrootd --dates "2020/12/*"

#python tally_access_info.py --source classads --dates "2020/01/*"
#python tally_access_info.py --source classads --dates "2020/02/*"
#python tally_access_info.py --source classads --dates "2020/03/*"
#python tally_access_info.py --source classads --dates "2020/04/*"
#python tally_access_info.py --source classads --dates "2020/05/*"
#python tally_access_info.py --source classads --dates "2020/06/*"
#python tally_access_info.py --source classads --dates "2020/07/*"
#python tally_access_info.py --source classads --dates "2020/08/*"
#python tally_access_info.py --source classads --dates "2020/09/*"
#python tally_access_info.py --source classads --dates "2020/10/*"
#python tally_access_info.py --source classads --dates "2020/11/*"
#python tally_access_info.py --source classads --dates "2020/12/*"

python tally_access_info.py --source cmssw --dates "2019/05/*"
python tally_access_info.py --source cmssw --dates "2019/08/*"

python tally_access_info.py --source xrootd --dates "2019/01/*"
python tally_access_info.py --source xrootd --dates "2019/02/*"
python tally_access_info.py --source xrootd --dates "2019/03/*"
python tally_access_info.py --source xrootd --dates "2019/04/*"
python tally_access_info.py --source xrootd --dates "2019/05/*"
python tally_access_info.py --source xrootd --dates "2019/06/*"
python tally_access_info.py --source xrootd --dates "2019/07/*"
python tally_access_info.py --source xrootd --dates "2019/08/*"
python tally_access_info.py --source xrootd --dates "2019/09/*"
python tally_access_info.py --source xrootd --dates "2019/10/*"
python tally_access_info.py --source xrootd --dates "2019/11/*"
python tally_access_info.py --source xrootd --dates "2019/12/*"
